### PR TITLE
Upgraded to Grails 2.5.0, plus some features, like ability to enable/disable cache prefix through Config.

### PR DESCRIPTION
**Pull request by donbeave**
Usage.

Add following code to your Config file:
```groovy
grails.cache.redis.usePrefix = true
```

### CODE REVIEW

**Comment by donbeave** [comment]
Added support for Grails 2.5.0.

**Comment by graemerocher** [comment]
Could you please rebase as there are merge conflicts?

**Comment by donbeave** [comment]
Done.

**Comment by graemerocher** [comment]
Thanks!

**Comment by donbeave** [comment]
@graemerocher when you prepare to release it?

**Pull request merged**
